djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('votacao/', include('votacao.urls')),
    path('admin/', admin.site.urls),
]

djangoProject/votacao/urls.py
from django.urls import path
from . import views

app_name = 'votacao'
urlpatterns = [
    # ex: votacao/
    path("", views.index, name='index'),
    # ex votacao/criarquestao
    path("criarquestao", views.criarquestao, name='criarquestao'),
    # ex votacao/1/criarquestao
    path('<int:questao_id>/criaropcao', views.criaropcao, name='criaropcao'),
    # ex: votacao/1
    path('<int:questao_id>', views.detalhe, name='detalhe'),
    # ex: votacao/3/resultados
    path('<int:questao_id>/resultados', views.resultados, name='resultados'),
    # ex: votacao/5/voto
    path('<int:questao_id>/voto', views.voto, name='voto'),
    # ex: votacao/register
    path('register/', views.register, name='register'),
    # ex: votacao/login
    path('login/', views.login, name='login'),
    # ex: votacao/logout
    path('logout/', views.logout, name='logout'),
    # ex: votacao/personalinfo
    path('personalinfo/', views.personalinfo, name='personalinfo'),
    # ex votacao/3/excluirquestao
    path('<int:questao_id>/excluirquestao', views.excluirquestao, name='excluirquestao'),
    # ex votacao/3/1/excluiropcao
    path('<int:questao_id>/<int:opcao_id>/exluiropcao', views.excluiropcao, name='excluiropcao'),



]

djangoProject/votacao/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User


# Questao:
# texto da questão e data de publicação
class Questao(models.Model):
    questao_texto = models.CharField(max_length=200)
    pub_data = models.DateTimeField('data de publicacao')

    def __str__(self):
        return self.questao_texto

    def foi_publicada_recentemente(self):
        return self.pub_data >= timezone.now() - datetime.timedelta(days=1)
# Opcao:
# texto da opção e número de votos
# chave estrangeira muitos-para-um pois uma Questao pode ter várias instancias de Opcao
class Opcao(models.Model):
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    opcao_texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

    def __str__(self):
        return self.opcao_texto

##
class Aluno(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    curso = models.CharField(max_length=50)
    numero_votos = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

djangoProject/votacao/views.py
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Questao, Opcao, Aluno
from django.utils import timezone
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.shortcuts import render


VOTOS_MAXIMOS = 40


def index(request):
    latest_question_list = Questao.objects.order_by('-pub_data')[:5]
    context = {'latest_question_list': latest_question_list}
    user = request.user
    if user.is_authenticated and not user.is_superuser:
        aluno = get_object_or_404(Aluno, user_id=user.id)
        context.update({"aluno": aluno})
    return render(request, 'votacao/index.html', context)


# ...
def detalhe(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/detalhe.html', {'questao': questao})


def voto(request, questao_id):
    if not request.user.is_authenticated:
        raise PermissionDenied()
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        opcao_seleccionada = questao.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        # Apresenta de novo o form para votar
        return render(request, 'votacao/detalhe.html',
                      {'questao': questao, 'error_message': "Não escolheu uma opção", })
    else:
        if not request.user.is_superuser:
            aluno = get_object_or_404(Aluno, user_id=request.user.id)
            if aluno.numero_votos < VOTOS_MAXIMOS:
                aluno.numero_votos += 1
                aluno.save()
            else:
                return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': f"Utilizador {request.user} atingiu o máximo de votos", })
        opcao_seleccionada.votos += 1
        opcao_seleccionada.save()
        return HttpResponseRedirect(reverse('votacao:resultados', args=(questao.id,)))

def resultados(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    return render(request, 'votacao/resultados.html', {'questao': questao})


def criarquestao(request):
    if not request.user.is_superuser:
        raise PermissionDenied()

    if request.method == 'POST':
        try:
            input = request.POST['questao']
            questao = Questao(questao_texto=input, pub_data=timezone.now())
            questao.save()
        except:
            return render(request, 'votacao/criarquestao.html', {'error_message': "Erro ao criar questão", })
        return HttpResponseRedirect(reverse('votacao:index'))
    return render(request, 'votacao/criarquestao.html')


def criaropcao(request, questao_id):
    if not request.user.is_superuser:
        raise PermissionDenied()
    questao = get_object_or_404(Questao, pk=questao_id)
    if request.method == 'POST':
        try:
            opcao = request.POST['opcao']
        except:
            # Apresenta de novo o form para votar
            return render(request, 'votacao/criaropcao.html',
                              {'questao': questao, 'error_message': "Erro ao criar opçao", })
        else:
            questao.opcao_set.create(opcao_texto=opcao, votos=0)
            return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))
    return render(request, 'votacao/criaropcao.html', {'questao': questao})





def register(request):
    if request.method == 'POST':
        try:
            username = str(request.POST['username'])
            email = str(request.POST['email'])
            curso = str(request.POST['curso'])
            password = str(request.POST['password'])
            u = User.objects.create_user(username=username, email=email, password=password)
            a = Aluno(user=u, curso=curso)
            a.save()

        except:
            return render(request, 'votacao/register.html', {'error_message': "Erro ao registar novo utilizador"})
        return HttpResponseRedirect(reverse('votacao:login'))
    return render(request, 'votacao/register.html')


def login(request):
    if request.method == 'POST':
        try:
            username = str(request.POST['username'])
            password = str(request.POST['password'])
            u = authenticate(request, username=username, password=password)
            if u is not None:
                django_login(request, u)
                return HttpResponseRedirect(reverse('votacao:index'))
            else:
                return render(request, 'votacao/login.html', {'error_message': "Login failed"})
        except Exception as e:
            print(str(e))
            return render(request, 'votacao/login.html', {'error_message': "Erro ao efetuar o login"})
    return render(request, 'votacao/login.html')


def logout(request):
    django_logout(request)
    return HttpResponseRedirect(reverse('votacao:index'))


def personalinfo(request):
    if not request.user.is_authenticated:
        return render(request, 'votacao/login.html')
    aluno = get_object_or_404(Aluno, user_id=request.user.id)
    return render(request, 'votacao/personalinfo.html', {'aluno': aluno})

def excluirquestao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        questao.delete()
    except:
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Erro ao excluir questão", })
    else:
        return HttpResponseRedirect(reverse('votacao:index'))


def excluirquestao(request, questao_id):
    if not request.user.is_superuser:
        raise PermissionDenied()
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        questao.delete()
    except:
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Erro ao excluir questão", })
    else:
        return HttpResponseRedirect(reverse('votacao:index'))


def excluiropcao(request, questao_id, opcao_id):
    if not request.user.is_superuser:
        raise PermissionDenied()
    questao = get_object_or_404(Questao, pk=questao_id)
    opcao = get_object_or_404(Opcao, pk=opcao_id)
    try:
         opcao.delete()
    except:
        return render(request, 'votacao/detalhe.html', {'questao': questao, 'error_message': "Erro ao excluir opção", })
    else:
        return HttpResponseRedirect(reverse('votacao:detalhe', args=(questao.id,)))

djangoProject/templates/votacao/criaropcao.html
<!DOCTYPE html>
<html>
<head>
	<title>Gravar nova opção</title>
	<style>
		form {
			display: flex;
			flex-direction: column;
			align-items: center;
			margin-top: 50px;
		}

        h1 {
            text-align: center;
        }

		label {
			font-size: 1.2em;
			margin-bottom: 10px;
		}

		input[type="text"] {
			padding: 10px;
			font-size: 1.2em;
			border: 1px solid #ccc;
			border-radius: 5px;
			margin-bottom: 20px;
			width: 300px;
		}

		input[type="submit"] {
			padding: 10px 20px;
			font-size: 1.2em;
			background-color: #4CAF50;
			color: white;
			border: none;
			border-radius: 5px;
			cursor: pointer;
			transition: background-color 0.3s ease;
		}

		input[type="submit"]:hover {
			background-color: #3e8e41;
		}
	</style>
</head>
<body>
	<h1>{{ questao.questao_texto }}</h1>
	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}
	<form action="#" method="post">
		{% csrf_token %}
	    <label for="opcao">Texto da nova opção: </label>
		<input type="text" name="opcao" id="opcao" />
		<input type="submit" value="Gravar nova opção" />
	</form>
</body>
</html>

djangoProject/templates/votacao/criarquestao.html
<style>
    form {
  margin: 20px auto;
  width: 50%;
  border: 1px solid #ccc;
  padding: 20px;
  border-radius: 5px;
        text-align: center;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
}

label {
  display: block;
  margin-bottom: 10px;
  font-weight: bold;
}

input[type="text"] {
  display: block;
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  margin-bottom: 20px;
}

input[type="submit"] {
  background-color: #4CAF50;
  border: none;
  color: white;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin-top: 20px;
  cursor: pointer;
  border-radius: 5px;
}

input[type="submit"]:hover {
  background-color: #3e8e41;
}

</style>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="#"
method="post">
{% csrf_token %}
    <label for="questao">Texto da nova questão: </label>
<input type="text" name="questao" id="questao" />
<input type="submit" value="Gravar nova questão" />
</form>

djangoProject/templates/votacao/detalhe.html
<!DOCTYPE html>
<html>
<head>
	<title>Vote</title>
	<style>
		body {

			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
			color: #333;
			margin: 0;
			padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
		}

		h1 {
			font-size: 2.5rem;
			margin: 1rem 0;
		}

		.form_div {
			display: flex;
            flex-direction: row;
            align-items: center;
            margin-top: 50px;
            font-size: 24px;
			gap: 30px;
			text-align: center;
		}

		.form_sub_div {
			display: flex;
			flex-direction: row;
			align-items: center;
			gap: 10px;
		}

		form{
			display: flex;
			flex-direction: column;
			align-items: center;
		}

		label {
			display: block;
            text-align: center;
			font-size: 1.2rem;
			font-weight: bold;
		}

		input[type="radio"] {
			margin-right: 0.5rem;
		}

		input[type="submit"] {
			margin-top: 1.5rem;
			background-color: #4CAF50;
			color: white;
			border: none;
			padding: 0.5rem 1rem;
			border-radius: 4px;
			cursor: pointer;
			font-size: 1.2rem;
			font-weight: bold;
			transition: background-color 0.2s ease-in-out;
		}

		input[type="submit"]:hover {
			background-color: #3e8e41;
		}

		button {
			margin-top: 1.5rem;
			background-color: #4CAF50;
			color: white;
			border: none;
			padding: 0.5rem 1rem;
			border-radius: 4px;
			cursor: pointer;
			font-size: 1.2rem;
			font-weight: bold;
			transition: background-color 0.2s ease-in-out;
		}

		button:hover {
			background-color: #3e8e41;
		}

		p {
			font-size: 1.2rem;
			margin: 1rem 0;
		}

		button.red_button {
			background-color: #ff2400 ;
		}

		.login_div {
			display: flex;
			flex-direction: row;
			align-items: center;
			gap: 20px;
			margin-top: 30px;
		}

		button.center {
			margin: 0;
		}

	</style>
</head>
<body>
	<h1>{{ questao.questao_texto }}</h1>
	{% if error_message %}
		<p style="color: #ff2400"><strong>{{ error_message }}</strong></p>
	{% endif %}
	<form action="{% url 'votacao:voto' questao.id %}" method="post">
		{% csrf_token %}
		<div class="form_div">
		{% for opcao in questao.opcao_set.all %}
			<div class="form_sub_div">
				<input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}" />
				<label for="opcao{{ forloop.counter }}">{{ opcao.opcao_texto }}</label>
				{% if user.is_superuser %}
					<a href="{% url 'votacao:excluiropcao' questao.id opcao.id%}" > <button type="button" class="red_button center" > Excluir</button> </a>
				{% endif %}
				<br />
			</div>
		{% endfor %}
		</div>
		{% if user.is_authenticated %}
			<input type="submit" value="Voto" />
		{% else %}
		<div class="login_div">
			<p><strong>Para votar precisa de efetuar o login</strong></p>
			<a href="{% url 'votacao:login' %}"><button type="button" class="center">Login</button></a>
		</div>
		{% endif %}
	</form>
	{% if user.is_superuser %}
		<a href="{% url 'votacao:criaropcao' questao.id%}" ><button> Criar Opção </button></a>
		<a href="{% url 'votacao:excluirquestao' questao.id%}" ><button class="red_button"> Excluir questão </button></a>
	{% endif %}
</body>
</html>

djangoProject/templates/votacao/index.html
<style>

    body {
        display: flex;
        flex-direction: column;
        align-items: center;
        font-family: Arial, sans-serif;
        background-color: #f2f2f2;
        color: #333;
    }

    /* Style for the question list */
    .question-list {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }

    /* Style for each question item */
    .question-item {
        margin: 10px;
        padding: 10px;
        background-color: #f5f5f5;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    }

    .question-item:hover {
        background-color: #f2f2f2;
    }

    /* Style for the "Create Question" button */
    .create-question-btn {
        display: block;
        width: 200px;
        margin: 20px auto;
        padding: 10px;
        background-color: #4CAF50;
        color: #fff !important;
        text-align: center;
        text-decoration: none;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
        transition: background-color 0.3s ease-in-out;
    }

    .create-question-btn:hover {
        background-color: #3e8e41;
    }

    a,
    a:visited {
        color: #000;
        text-decoration: none;
    }

    .login_div {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: flex-end;
        width: 100%;
        gap: 15px;
        margin-right: 20px;
        height: 51px;
    }

    button {
        background-color: #4CAF50;
        color: white;
        padding: 4px 6px;
        border: none;
        border-radius: 16px;
        cursor: pointer;
        font-size: 12px;
        width: 50px;
    }

    p {
        margin: 0;
    }


</style>
<div class="login_div">
    {% if user.is_authenticated %}
    <div class="loged_data_div">
        <p>Logged in as <b>{{request.user}}</b> {% if user.is_superuser %} (Admin){% endif %}</p>
        {% if not user.is_superuser %}
        <p>Numero de votos: <b>{{aluno.numero_votos}}</b></p>
        {% endif %}
    </div>
    <a href="{% url 'votacao:logout' %}">
        <button>Logout</button>
    </a>
    {% else %}
    <a href="{% url 'votacao:login' %}">
        <button>Login</button>
    </a>
    {% endif %}
</div>
{% if latest_question_list %}

<ul class="question-list">
    {% for questao in latest_question_list %}
    <a href="{% url 'votacao:detalhe' questao.id %}">
        <li class="question-item">

            {{ questao.questao_texto }}

        </li>
    </a>
    {% endfor %}
</ul>
{% if user.is_superuser %}
<a href="{% url 'votacao:criarquestao' %}" class="create-question-btn">Criar Questão</a>
{% endif %}
{% else %}
<p>Não há questões disponíveis.</p>
{% endif %}

djangoProject/templates/votacao/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>

        body {

			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
			color: #333;
        }
        /* Style for the page title */
        h1 {
            text-align: center;
            margin-top: 50px;
            font-size: 36px;
        }

        /* Style for the error message */
        .error-message {
            text-align: center;
            color: red;
            margin-top: 20px;
            margin-bottom: 0;
            font-size: 18px;
        }

        /* Style for the form */
        form {
            display: flex;
            flex-direction: column;
            align-items: center;
            margin-top: 50px;
            font-size: 24px;
        }

        /* Style for the labels */
        label {
            margin-bottom: 10px;
            font-weight: bold;
        }

        /* Style for the input fields */
        input[type=text], input[type=password] {
            width: 40%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
            border: none;
            border-bottom: 2px solid #ddd;
            border-radius: 16px;
        }

        /* Style for the submit button */
        input[type=submit] {
            background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 20px 0;
            border: none;
            border-radius: 16px;
            cursor: pointer;
            font-size: 24px;
        }

        /* Hover effect for the submit button */
        input[type=submit]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
<h1>Login</h1>
{% if error_message %}
<p class="error-message"><strong>{{ error_message }}</strong></p>
{% endif %}
<form method="POST" action="{% url 'votacao:login' %}">
    {% csrf_token %}
    <label for="username">Nome de usuário:</label>
    <input type="text" id="username" name="username" required>
    <label for="password">Senha:</label>
    <input type="password" id="password" name="password" required>
    <input type="submit" value="Entrar">
</form>
</body>
</html>

djangoProject/templates/votacao/personalinfo.html
<!DOCTYPE html>
<html>
<head>
	<title>User Info</title>
	<style>
        /* Style for the page title */
        h1 {
            text-align: center;
            margin-top: 50px;
            font-size: 36px;
        }

        /* Style for the user info */
        p {
            margin-top: 20px;
            margin-bottom: 10px;
            font-size: 24px;
        }

        /* Style for the welcome message */
        .welcome {
            text-align: center;
            margin-top: 50px;
            font-size: 36px;
        }

        /* Style for the login and register links */
        a {
            color: #4CAF50;
            text-decoration: none;
        }
    </style>
</head>
<body>
	{% if request.user.is_authenticated %}
		<h1>User Info</h1>
		<p><strong>Username:</strong> {{ aluno.user.username }}</p>
		<p><strong>Course:</strong> {{ aluno.curso }}</p>
		<p><strong>Email:</strong> {{ aluno.user.email }}</p>
	{% else %}
		<div class="welcome">
			<h1>Welcome!</h1>
			<p>Please <a href="{% url 'login' %}">login</a> or <a href="{% url 'register' %}">register</a> to access user info.</p>
		</div>
	{% endif %}
</body>
</html>

djangoProject/templates/votacao/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Registrar novo usuário</title>
</head>
<body>

<h1>Registrar novo usuário</h1>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form method="POST" action="{% url 'votacao:register' %}">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br><br>
    <label for="email">E-mail:</label>
    <input type="email" id="email" name="email" required><br><br>
    <label for="curso">Curso:</label>
    <input type="text" id="curso" name="curso" required><br><br>
    <input type="submit" value="Registrar">
</form>
</body>
</html>

djangoProject/templates/votacao/resultados.html
<!DOCTYPE html>
<html>
<head>
	<title>Results</title>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f2f2f2;
			color: #333;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
		h1 {
			margin-top: 50px;
			text-align: center;
			font-size: 36px;
			font-weight: bold;
			text-transform: uppercase;
			letter-spacing: 2px;
		}
		ul {
         width: 40%;
			list-style: none;
			padding: 0;
			margin: 20px 0;
		}
		li {
			background-color: #fff;
			padding: 10px;
			margin-bottom: 10px;
			border-radius: 5px;
			box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
		}
		li:hover {
			background-color: #f2f2f2;
		}
       button {
        background-color: #4CAF50;
            color: white;
            padding: 14px 20px;
            margin: 20px 0;
            border: none;
            border-radius: 16px;
            cursor: pointer;
            font-size: 24px;
       }
	</style>
</head>
<body>
	<h1>{{ questao.questao_texto }}</h1>
	<ul>
		{% for opcao in questao.opcao_set.all %}
			<li>{{ opcao.opcao_texto }} -- {{ opcao.votos }} voto{{ opcao.votos|pluralize }}</li>
		{% endfor %}
	</ul>
	<a href="{% url 'votacao:detalhe' questao.id %}"><button>Votar novamente?</button></a>
</body>
</html>